# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("clients", "0001_initial"),
        ("ledger", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_code", models.CharField(max_length=20)),
                ("product_name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Savings"),
                            ("FIXED_DEPOSIT", "Fixed Deposit"),
                            ("CURRENT", "Current"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interest_rate_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=7),
                ),
                (
                    "min_balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("notice_period_days", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "deposit_products",
                "unique_together": {("tenant", "product_code")},
            },
        ),
        migrations.CreateModel(
            name="DepositAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=3)),
                (
                    "balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DORMANT", "Dormant"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateField()),
                ("closed_at", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_accounts",
                        to="clients.client",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="deposits.depositproduct",
                    ),
                ),
            ],
            options={
                "db_table": "deposit_accounts",
                "unique_together": {("tenant", "account_number")},
            },
        ),
        migrations.CreateModel(
            name="DepositTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synced"),
                            ("PENDING_UPLOAD", "Pending Upload"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("server_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("INTEREST_CREDIT", "Interest Credit"),
                            ("FEE_DEBIT", "Fee Debit"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                ("balance_after", models.DecimalField(decimal_places=4, max_digits=19)),
                ("description", models.TextField(blank=True)),
                ("payment_method", models.CharField(blank=True, max_length=20)),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="deposits.depositaccount",
                    ),
                ),
                (
                    "gl_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ledger.gltransaction",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "deposit_transactions",
            },
        ),
    ]
