# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("clients", "0001_initial"),
        ("loans", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditScoreModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(max_length=100)),
                ("model_version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "criteria",
                    models.JSONField(
                        help_text="Array of scoring criteria with weights"
                    ),
                ),
                (
                    "score_ranges",
                    models.JSONField(
                        default=list,
                        help_text="Score ranges with labels and recommendations",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "credit_score_models",
                "unique_together": {("tenant", "model_name", "model_version")},
            },
        ),
        migrations.CreateModel(
            name="ClientCreditScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("risk_label", models.CharField(max_length=20)),
                ("recommendation", models.CharField(max_length=30)),
                (
                    "component_scores",
                    models.JSONField(help_text="Breakdown by criteria"),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "computed_for",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOAN_APPLICATION", "Loan Application"),
                            ("PERIODIC_REVIEW", "Periodic Review"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("overridden", models.BooleanField(default=False)),
                (
                    "override_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("override_reason", models.TextField(blank=True)),
                ("overridden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_scores",
                        to="clients.client",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_scores",
                        to="loans.loan",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="scoring.creditscoremodel",
                    ),
                ),
            ],
            options={
                "db_table": "client_credit_scores",
                "indexes": [
                    models.Index(
                        fields=["tenant", "client", "-computed_at"],
                        name="idx_scores_client",
                    )
                ],
            },
        ),
    ]
