# Generated by Django 5.1.15 on 2026-03-16 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_token_hash", models.CharField(max_length=255)),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DESKTOP", "Desktop"),
                            ("TABLET", "Tablet"),
                            ("MOBILE", "Mobile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("device_info", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("location_country", models.CharField(blank=True, max_length=2)),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "terminated_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOGOUT", "Logout"),
                            ("TIMEOUT", "Timeout"),
                            ("ADMIN_KILL", "Admin Kill"),
                            ("SUSPICIOUS", "Suspicious"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "active_sessions",
            },
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "approval_decisions",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_type", models.CharField(max_length=100)),
                ("target_table", models.CharField(max_length=100)),
                ("target_id", models.UUIDField()),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "approval_requests",
            },
        ),
        migrations.CreateModel(
            name="IpWhitelist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ip_range",
                    models.CharField(
                        help_text="CIDR notation e.g. 192.168.1.0/24", max_length=50
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ip_whitelists",
            },
        ),
        migrations.CreateModel(
            name="MakerCheckerConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_type", models.CharField(max_length=100)),
                ("min_approvals", models.IntegerField(default=1)),
                ("required_roles", models.JSONField(default=list)),
                (
                    "amount_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("amount_currency", models.CharField(blank=True, max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "maker_checker_configs",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("permission_code", models.CharField(max_length=100, unique=True)),
                ("resource", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "permissions",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role_code", models.CharField(max_length=50)),
                ("role_name", models.CharField(max_length=100)),
                ("is_system_role", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "role_permissions",
            },
        ),
        migrations.CreateModel(
            name="SessionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role_code",
                    models.CharField(
                        blank=True,
                        help_text="Blank = applies to all roles",
                        max_length=50,
                    ),
                ),
                ("session_timeout_minutes", models.IntegerField(default=480)),
                ("max_concurrent_sessions", models.IntegerField(default=3)),
                ("require_ip_whitelist", models.BooleanField(default=False)),
                ("require_mfa", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "session_configs",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "auth_user_id",
                    models.UUIDField(
                        help_text="FK to Supabase auth.users", unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("failed_login_count", models.IntegerField(default=0)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_enabled", models.BooleanField(default=False)),
                ("language_preference", models.CharField(default="en", max_length=5)),
                (
                    "theme_preference",
                    models.CharField(default="professional_light", max_length=30),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_roles",
            },
        ),
    ]
