# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activesession",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="approvaldecision",
            name="approval_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="accounts.approvalrequest",
            ),
        ),
        migrations.AddField(
            model_name="ipwhitelist",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="makercheckerconfig",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="accounts.permission",
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="sessionconfig",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="tenants.branch",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ipwhitelist",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="approvaldecision",
            name="decided_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_decisions",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="activesession",
            name="terminated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="activesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.user",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="accounts.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="makercheckerconfig",
            unique_together={("tenant", "action_type", "amount_threshold")},
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("tenant", "role_code")},
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "permission")},
        ),
        migrations.AlterUniqueTogether(
            name="sessionconfig",
            unique_together={("tenant", "role_code")},
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("tenant", "email")},
        ),
        migrations.AddIndex(
            model_name="activesession",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["tenant", "user", "is_active"],
                name="idx_sessions_active",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role")},
        ),
    ]
