# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key_prefix", models.CharField(max_length=8)),
                ("key_hash", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=100)),
                ("permissions", models.JSONField(default=list)),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("allowed_ips", models.JSONField(blank=True, default=list)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "api_keys",
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                ("target_url", models.TextField()),
                ("secret_hash", models.CharField(max_length=255)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("retry_count", models.IntegerField(default=3)),
                ("retry_delay_seconds", models.IntegerField(default=60)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.IntegerField(blank=True, null=True)),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("attempt_number", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="integrations.webhook",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_deliveries",
            },
        ),
        migrations.CreateModel(
            name="SyncQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_id", models.CharField(max_length=100)),
                ("target_table", models.CharField(max_length=100)),
                ("target_sync_id", models.UUIDField()),
                (
                    "operation",
                    models.CharField(
                        choices=[("INSERT", "Insert"), ("UPDATE", "Update")],
                        max_length=10,
                    ),
                ),
                ("payload", models.JSONField()),
                ("client_timestamp", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("APPLIED", "Applied"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "sync_queue",
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "QUEUED")),
                        fields=["tenant", "status"],
                        name="idx_sync_pending",
                    )
                ],
            },
        ),
    ]
