# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryPack",
            fields=[
                (
                    "country_code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("country_name", models.CharField(max_length=100)),
                ("regulatory_authority", models.CharField(max_length=255)),
                ("default_currency", models.CharField(max_length=3)),
                ("data_protection_law", models.CharField(blank=True, max_length=255)),
                ("data_localisation_required", models.BooleanField(default=False)),
                ("aml_supervisory_body", models.CharField(blank=True, max_length=255)),
                ("audit_retention_years", models.IntegerField(default=7)),
                ("default_language", models.CharField(default="en", max_length=5)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Full country pack configuration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "country_packs",
            },
        ),
        migrations.CreateModel(
            name="LicenceTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tier_code", models.CharField(max_length=50)),
                ("tier_name", models.CharField(max_length=255)),
                ("can_accept_deposits", models.BooleanField(default=False)),
                ("can_offer_savings", models.BooleanField(default=False)),
                ("can_do_transfers", models.BooleanField(default=False)),
                ("credit_only", models.BooleanField(default=False)),
                (
                    "min_capital_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("min_capital_currency", models.CharField(blank=True, max_length=3)),
                (
                    "car_requirement_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "single_obligor_limit_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "insider_lending_limit_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "reporting_frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("AD_HOC", "Ad Hoc"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licence_tiers",
                        to="tenants.countrypack",
                    ),
                ),
            ],
            options={
                "db_table": "licence_tiers",
                "unique_together": {("country", "tier_code")},
            },
        ),
        migrations.CreateModel(
            name="RuleSetVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("INTEREST_FORMULA", "Interest Formula"),
                            ("LOAN_CLASSIFICATION", "Loan Classification"),
                            ("PROVISIONING", "Provisioning"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version_code", models.CharField(max_length=50)),
                ("version_number", models.IntegerField()),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("config", models.JSONField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("change_justification", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_rule_sets",
                        to="accounts.user",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_set_versions",
                        to="tenants.countrypack",
                    ),
                ),
            ],
            options={
                "db_table": "rule_set_versions",
                "unique_together": {
                    ("country", "rule_type", "version_code", "version_number")
                },
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("trading_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("subscription_active", models.BooleanField(default=True)),
                ("default_currency", models.CharField(max_length=3)),
                ("default_language", models.CharField(default="en", max_length=5)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("logo_url", models.TextField(blank=True)),
                ("primary_brand_colour", models.CharField(blank=True, max_length=7)),
                ("secondary_brand_colour", models.CharField(blank=True, max_length=7)),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("data_localisation_required", models.BooleanField(default=False)),
                ("data_centre_tag", models.CharField(blank=True, max_length=50)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenants",
                        to="tenants.countrypack",
                    ),
                ),
                (
                    "licence_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenants",
                        to="tenants.licencetier",
                    ),
                ),
            ],
            options={
                "db_table": "tenants",
            },
        ),
        migrations.CreateModel(
            name="LicenceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("licence_number", models.CharField(blank=True, max_length=100)),
                ("licensing_authority", models.CharField(blank=True, max_length=255)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("permitted_features", models.JSONField(default=dict)),
                ("aml_supervisory_body", models.CharField(blank=True, max_length=255)),
                ("str_required", models.BooleanField(default=True)),
                (
                    "kyc_minimum_level",
                    models.CharField(default="FULL_CDD", max_length=20),
                ),
                (
                    "active_classification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.rulesetversion",
                    ),
                ),
                (
                    "active_interest_formula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.rulesetversion",
                    ),
                ),
                (
                    "active_provisioning",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.rulesetversion",
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licence_profile",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "licence_profiles",
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branch_code", models.CharField(max_length=20)),
                ("branch_name", models.CharField(max_length=255)),
                (
                    "branch_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("URBAN", "Urban"),
                            ("PERI_URBAN", "Peri-Urban"),
                            ("RURAL", "Rural"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "branches",
                "unique_together": {("tenant", "branch_code")},
            },
        ),
    ]
