# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("clients", "0001_initial"),
        ("deposits", "0001_initial"),
        ("ledger", "0001_initial"),
        ("loans", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileMoneyProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_code", models.CharField(max_length=30)),
                ("provider_name", models.CharField(max_length=100)),
                (
                    "api_type",
                    models.CharField(
                        choices=[
                            ("AFRICAS_TALKING", "Africa's Talking"),
                            ("DIRECT_API", "Direct API"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "api_config",
                    models.JSONField(
                        default=dict,
                        help_text="Encrypted API credentials and endpoints",
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("phone_prefix", models.CharField(blank=True, max_length=10)),
                (
                    "phone_regex",
                    models.CharField(
                        blank=True,
                        help_text="Validation regex for phone numbers",
                        max_length=100,
                    ),
                ),
                (
                    "min_transaction",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "max_transaction",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("fee_structure", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="momo_providers",
                        to="tenants.countrypack",
                    ),
                ),
                (
                    "settlement_gl_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ledger.glaccount",
                    ),
                ),
            ],
            options={
                "db_table": "mobile_money_providers",
                "unique_together": {("country", "provider_code")},
            },
        ),
        migrations.CreateModel(
            name="MobileMoneyReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reconciliation_date", models.DateField()),
                ("statement_file_path", models.TextField(blank=True)),
                (
                    "statement_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("statement_count", models.IntegerField(blank=True, null=True)),
                (
                    "system_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("system_count", models.IntegerField(blank=True, null=True)),
                ("matched_count", models.IntegerField(default=0)),
                ("unmatched_system", models.IntegerField(default=0)),
                ("unmatched_provider", models.IntegerField(default=0)),
                (
                    "variance_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("EXCEPTION", "Exception"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="mobile_money.mobilemoneyprovider",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "mobile_money_reconciliation",
            },
        ),
        migrations.CreateModel(
            name="MobileMoneyTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synced"),
                            ("PENDING_UPLOAD", "Pending Upload"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("server_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("COLLECTION", "Collection"),
                            ("DISBURSEMENT", "Disbursement"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("REVERSAL", "Reversal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "Inbound"), ("OUT", "Outbound")], max_length=3
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                ("currency", models.CharField(max_length=3)),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "fee_bearer",
                    models.CharField(
                        choices=[("CLIENT", "Client"), ("MFI", "MFI")],
                        default="CLIENT",
                        max_length=10,
                    ),
                ),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                ("internal_reference", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REVERSED", "Reversed"),
                            ("TIMEOUT", "Timeout"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reconciled", models.BooleanField(default=False)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="momo_transactions",
                        to="clients.client",
                    ),
                ),
                (
                    "deposit_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="momo_transactions",
                        to="deposits.depositaccount",
                    ),
                ),
                (
                    "gl_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ledger.gltransaction",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="momo_transactions",
                        to="loans.loan",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="mobile_money.mobilemoneyprovider",
                    ),
                ),
                (
                    "repayment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="momo_transactions",
                        to="loans.repayment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "mobile_money_transactions",
                "indexes": [
                    models.Index(fields=["tenant", "status"], name="idx_momo_status")
                ],
            },
        ),
    ]
