# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("CLIENTS", "Clients"),
                            ("LOANS", "Loans"),
                            ("REPAYMENT_HISTORY", "Repayment History"),
                            ("CHART_OF_ACCOUNTS", "Chart of Accounts"),
                            ("OPENING_BALANCES", "Opening Balances"),
                            ("DEPOSIT_ACCOUNTS", "Deposit Accounts"),
                            ("GROUPS", "Groups"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_path", models.TextField(help_text="Supabase Storage path")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("VALIDATING", "Validating"),
                            ("VALIDATION_COMPLETE", "Validation Complete"),
                            ("PREVIEWING", "Previewing"),
                            ("IMPORTING", "Importing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(blank=True, null=True)),
                ("valid_rows", models.IntegerField(blank=True, null=True)),
                ("error_rows", models.IntegerField(blank=True, null=True)),
                ("warning_rows", models.IntegerField(blank=True, null=True)),
                ("validation_errors", models.JSONField(default=list)),
                ("validation_warnings", models.JSONField(default=list)),
                ("imported_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "import_jobs",
            },
        ),
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text="Array of step objects with status"
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_steps", models.JSONField(default=list)),
                ("load_demo_data", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_progress",
            },
        ),
    ]
