# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSING", "Closing"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_periods",
                "unique_together": {("tenant", "period_name")},
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_currency", models.CharField(max_length=3)),
                ("target_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=19)),
                ("rate_date", models.DateField()),
                ("source", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "exchange_rates",
                "unique_together": {("base_currency", "target_currency", "rate_date")},
            },
        ),
        migrations.CreateModel(
            name="GlAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_code", models.CharField(max_length=20)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("INCOME", "Income"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_header",
                    models.BooleanField(
                        default=False, help_text="Summary account — no direct postings"
                    ),
                ),
                (
                    "is_system_account",
                    models.BooleanField(
                        default=False, help_text="Auto-created, cannot be deleted"
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")], max_length=1
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "regulatory_mapping_code",
                    models.CharField(
                        blank=True,
                        help_text="Maps to prudential return line item",
                        max_length=50,
                    ),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="ledger.glaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "gl_accounts",
                "unique_together": {("tenant", "account_code")},
            },
        ),
        migrations.CreateModel(
            name="GlTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synced"),
                            ("PENDING_UPLOAD", "Pending Upload"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("server_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                ("transaction_ref", models.CharField(max_length=50)),
                ("transaction_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOAN_DISBURSEMENT", "Loan Disbursement"),
                            ("REPAYMENT", "Repayment"),
                            ("DEPOSIT", "Deposit"),
                            ("MANUAL", "Manual"),
                            ("FEE", "Fee"),
                            ("PROVISION", "Provision"),
                            ("INTEREST_ACCRUAL", "Interest Accrual"),
                            ("MOBILE_MONEY", "Mobile Money"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("is_reversal", models.BooleanField(default=False)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="ledger.accountingperiod",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "reverses_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ledger.gltransaction",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "gl_transactions",
            },
        ),
        migrations.CreateModel(
            name="GlEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debit_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("currency", models.CharField(max_length=3)),
                ("description", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="ledger.glaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="ledger.gltransaction",
                    ),
                ),
            ],
            options={
                "db_table": "gl_entries",
                "indexes": [
                    models.Index(
                        fields=["tenant", "account"], name="idx_gl_entries_account"
                    )
                ],
            },
        ),
    ]
