# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("investor_name", models.CharField(max_length=255)),
                (
                    "investor_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("INSTITUTIONAL", "Institutional"),
                            ("FUND", "Fund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("investment_currency", models.CharField(max_length=3)),
                (
                    "invested_amount",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "invested_amount_local",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("investment_date", models.DateField()),
                (
                    "exchange_rate_at_investment",
                    models.DecimalField(decimal_places=8, max_digits=19),
                ),
                (
                    "current_value_local",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("EXITED", "Exited"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("covenant_thresholds", models.JSONField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investor_profiles",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "investor_profiles",
            },
        ),
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period", models.CharField(max_length=20)),
                (
                    "declared_rate_pct",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DECLARED", "Declared"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                            ("REINVESTED", "Reinvested"),
                        ],
                        default="DECLARED",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dividends",
                        to="investors.investorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "dividends",
            },
        ),
        migrations.CreateModel(
            name="InvestorShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=128, unique=True)),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_views", models.IntegerField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "investor_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="investors.investorprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "investor_share_links",
            },
        ),
    ]
