# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("clients", "0001_initial"),
        ("ledger", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_code", models.CharField(max_length=20)),
                ("product_name", models.CharField(max_length=255)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("GROUP", "Group"),
                            ("SME", "SME"),
                            ("EMERGENCY", "Emergency"),
                            ("AGRICULTURAL", "Agricultural"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_amount", models.DecimalField(decimal_places=4, max_digits=19)),
                ("max_amount", models.DecimalField(decimal_places=4, max_digits=19)),
                ("min_term_months", models.IntegerField()),
                ("max_term_months", models.IntegerField()),
                (
                    "interest_method",
                    models.CharField(
                        choices=[
                            ("FLAT", "Flat"),
                            ("REDUCING_BALANCE", "Reducing Balance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_interest_rate_pct",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                (
                    "origination_fee_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "insurance_fee_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("requires_collateral", models.BooleanField(default=False)),
                ("requires_guarantor", models.BooleanField(default=False)),
                (
                    "group_liability_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JOINT", "Joint Liability"),
                            ("INDIVIDUAL", "Individual Liability"),
                        ],
                        max_length=20,
                    ),
                ),
                ("allowed_frequencies", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "loan_products",
                "unique_together": {("tenant", "product_code")},
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synced"),
                            ("PENDING_UPLOAD", "Pending Upload"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("server_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                ("loan_number", models.CharField(max_length=50)),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "interest_rate_pct",
                    models.DecimalField(decimal_places=4, max_digits=7),
                ),
                ("interest_method", models.CharField(max_length=20)),
                ("term_months", models.IntegerField()),
                (
                    "repayment_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("FORTNIGHTLY", "Fortnightly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "origination_fee",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "insurance_fee",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "total_interest",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "total_repayable",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "outstanding_principal",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "outstanding_interest",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "arrears_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("days_past_due", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLICATION", "Application"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("DISBURSED", "Disbursed"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("WRITTEN_OFF", "Written Off"),
                            ("RESTRUCTURED", "Restructured"),
                        ],
                        default="APPLICATION",
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("WATCH", "Watch"),
                            ("SUBSTANDARD", "Substandard"),
                            ("DOUBTFUL", "Doubtful"),
                            ("LOSS", "Loss"),
                        ],
                        default="CURRENT",
                        max_length=20,
                    ),
                ),
                (
                    "provision_rate_pct",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "provision_amount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("application_date", models.DateField()),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                ("maturity_date", models.DateField(blank=True, null=True)),
                ("first_repayment_date", models.DateField(blank=True, null=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                (
                    "affordability_dti_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("collateral_description", models.TextField(blank=True)),
                (
                    "collateral_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("is_insider_loan", models.BooleanField(default=False)),
                ("override_flag", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True)),
                ("is_test_data", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="tenants.branch",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="clients.client",
                    ),
                ),
                (
                    "disbursed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans",
                        to="clients.group",
                    ),
                ),
                (
                    "guarantor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clients.client",
                    ),
                ),
                (
                    "interest_formula_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tenants.rulesetversion",
                    ),
                ),
                (
                    "loan_officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_loans",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="loans.loanproduct",
                    ),
                ),
            ],
            options={
                "db_table": "loans",
            },
        ),
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("instalment_number", models.IntegerField()),
                ("due_date", models.DateField()),
                ("principal_due", models.DecimalField(decimal_places=4, max_digits=19)),
                ("interest_due", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "fees_due",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("total_due", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "principal_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "interest_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "fees_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("days_late", models.IntegerField(default=0)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="loans.loan",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "repayment_schedules",
            },
        ),
        migrations.CreateModel(
            name="Repayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synced"),
                            ("PENDING_UPLOAD", "Pending Upload"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("server_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=19)),
                ("currency", models.CharField(max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("received_at", models.DateTimeField()),
                (
                    "principal_applied",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "interest_applied",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "fees_applied",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "penalty_applied",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("receipt_number", models.CharField(blank=True, max_length=50)),
                ("reversed", models.BooleanField(default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True)),
                (
                    "gl_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ledger.gltransaction",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repayments",
                        to="loans.loan",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repayments",
                        to="loans.repaymentschedule",
                    ),
                ),
            ],
            options={
                "db_table": "repayments",
            },
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["tenant", "status"], name="idx_loans_status"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["tenant", "client"], name="idx_loans_client"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["tenant", "classification"], name="idx_loans_class"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="loan",
            unique_together={("tenant", "loan_number")},
        ),
        migrations.AlterUniqueTogether(
            name="repaymentschedule",
            unique_together={("loan", "instalment_number")},
        ),
    ]
