# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("sync_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synced"),
                            ("PENDING_UPLOAD", "Pending Upload"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("server_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("SME", "SME"),
                            ("GROUP", "Group"),
                        ],
                        max_length=20,
                    ),
                ),
                ("client_number", models.CharField(max_length=50)),
                ("full_legal_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("national_id_type", models.CharField(blank=True, max_length=50)),
                ("national_id_number", models.CharField(blank=True, max_length=100)),
                ("id_issue_date", models.DateField(blank=True, null=True)),
                ("id_expiry_date", models.DateField(blank=True, null=True)),
                ("phone_primary", models.CharField(blank=True, max_length=20)),
                ("phone_secondary", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=255)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("employer_name", models.CharField(blank=True, max_length=255)),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("income_currency", models.CharField(blank=True, max_length=3)),
                ("source_of_funds", models.CharField(blank=True, max_length=255)),
                (
                    "risk_rating",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "is_pep",
                    models.BooleanField(
                        default=False, verbose_name="Politically Exposed Person"
                    ),
                ),
                ("is_insider", models.BooleanField(default=False)),
                ("insider_relationship", models.CharField(blank=True, max_length=100)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("INCOMPLETE", "Incomplete"),
                            ("COMPLETE", "Complete"),
                            ("VERIFIED", "Verified"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="INCOMPLETE",
                        max_length=20,
                    ),
                ),
                ("kyc_verified_at", models.DateTimeField(blank=True, null=True)),
                ("sanctions_checked", models.BooleanField(default=False)),
                ("sanctions_hit", models.BooleanField(default=False)),
                ("onboarding_blocked", models.BooleanField(default=False)),
                ("block_reason", models.TextField(blank=True)),
                ("is_test_data", models.BooleanField(default=False)),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_clients",
                        to="accounts.user",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to="tenants.branch",
                    ),
                ),
                (
                    "kyc_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synced"),
                            ("PENDING_UPLOAD", "Pending Upload"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("server_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                ("group_name", models.CharField(max_length=255)),
                ("group_number", models.CharField(max_length=50)),
                (
                    "meeting_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("BIWEEKLY", "Biweekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("meeting_day", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="tenants.branch",
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_groups",
                        to="clients.client",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "groups",
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateField()),
                ("left_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="clients.client",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="clients.group",
                    ),
                ),
            ],
            options={
                "db_table": "group_members",
            },
        ),
        migrations.CreateModel(
            name="KycDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sync_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("SYNCED", "Synced"),
                            ("PENDING_UPLOAD", "Pending Upload"),
                            ("CONFLICT", "Conflict"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SYNCED",
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_created_at", models.DateTimeField(blank=True, null=True)),
                ("client_updated_at", models.DateTimeField(blank=True, null=True)),
                ("server_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID_SCAN", "ID Scan"),
                            ("PROOF_OF_ADDRESS", "Proof of Address"),
                            ("PHOTO", "Photo"),
                            ("SOURCE_OF_FUNDS", "Source of Funds"),
                            ("EDD_REPORT", "EDD Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_path", models.TextField(help_text="Supabase Storage path")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to="clients.client",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_documents",
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["tenant", "branch"], name="idx_clients_branch"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["tenant", "assigned_officer"], name="idx_clients_officer"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("tenant", "client_number")},
        ),
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("tenant", "group_number")},
        ),
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("group", "client")},
        ),
    ]
