# Generated by Django 5.1.15 on 2026-03-16 02:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_code", models.CharField(max_length=50, unique=True)),
                ("report_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FINANCIAL", "Financial"),
                            ("PORTFOLIO", "Portfolio"),
                            ("REGULATORY", "Regulatory"),
                            ("COMPLIANCE", "Compliance"),
                            ("OPERATIONAL", "Operational"),
                            ("INVESTOR", "Investor"),
                            ("BOARD", "Board"),
                        ],
                        max_length=30,
                    ),
                ),
                ("applicable_roles", models.JSONField(default=list)),
                (
                    "parameters",
                    models.JSONField(default=list, help_text="Parameter definitions"),
                ),
                ("output_formats", models.JSONField(default=list)),
                ("template_path", models.TextField(blank=True)),
                ("query_config", models.JSONField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "report_definitions",
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("schedule_name", models.CharField(max_length=255)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True, help_text="1=Monday for WEEKLY", null=True
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, help_text="1-28 for MONTHLY", null=True
                    ),
                ),
                ("time_of_day", models.TimeField(default="06:00:00")),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("output_format", models.CharField(default="PDF", max_length=10)),
                ("recipients", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField()),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.reportdefinition",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "report_schedules",
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parameters", models.JSONField(default=dict)),
                ("output_format", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.TextField(blank=True, help_text="Supabase Storage path"),
                ),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("generation_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.user",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="reports.reportdefinition",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="reports.reportschedule",
                    ),
                ),
            ],
            options={
                "db_table": "report_runs",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"], name="idx_report_runs_recent"
                    )
                ],
            },
        ),
    ]
